# handlers for the environment specific tasks of the common role

- name: restart postfix
  service: name=postfix state=restarted

- name: update postfix aliases database
  command: /usr/bin/newaliases

- name: restart rsyslog
  service: name=rsyslog state=restarted
