---
- name: Install required packages
  apt:
    name: postfix
    state: present

- include_vars:
    dir: "{{ inventory_dir }}/private/vhosts"
    name: vhost_specific_variables
  tags: apache, virtual_hosts

- name: Set vhosts
  tags: all
  set_fact:
    postfix_vhosts: "{% set postfix_vhosts = [] %}{% for d in vhost_specific_variables.values() %}{% if ('sympa' in d and 'server' in d.sympa and d.sympa.server == inventory_hostname) or inventory_hostname == 'local-proxy'  %}{% set _ = postfix_vhosts.append(mail|combine(d.common.mail, recursive=True)) %}{% endif %}{% endfor %}{{ postfix_vhosts }}"

- name: Set vhosts mail domains
  tags: all
  set_fact:
    mail_domains: "{% set mail_domains = [] %}{% for d in postfix_vhosts %}{% set _ = mail_domains.append(d.domain) %}{% endfor %}{{ mail_domains }}"

- name: Install Postfix main.cf configuration file
  template: src=main.cf.j2 dest=/etc/postfix/main.cf
  notify: restart postfix

- name: Enable Spamassassin in Postfix if needed.
  blockinfile:
    path: /etc/postfix/master.cf
    marker: "# {mark} ANSIBLE MANAGED Spamassassin config"
    block: |
      smtp inet n - n - - smtpd   -o content_filter=spamassassin:
      spamassassin unix - n n - - pipe flags=Rq user=debian-spamd argv=/usr/bin/spamc -s 20000000 -e /usr/sbin/sendmail -oi -f ${sender} ${recipient}
  notify: restart postfix
  when: common.mail.antispam is defined
