---

- name: "Install Sympa [1/3: configure]"
  command: ./configure --prefix={{ install_prefix }}/{{ sympa.install_dir_name }} --with-lockdir=/var/lock --without-initdir --with-unitsdir=/lib/systemd/system --with-spooldir=/var/spool/sympa --with-expldir={{ sympa.lists_path }}
  args:
    chdir: "{{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }}"
    executable: /bin/bash

- name: "Install Sympa [2/3: make]"
  command: make
  args:
    chdir: "{{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }}"
    executable: /bin/bash

- name: "Install Sympa [3/3: make install]"
  command: make install
  args:
    chdir: "{{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }}"
    executable: /bin/bash

- name: Fix ownership
  file:
    path: "{{ install_prefix }}/{{ sympa.install_dir_name }}"
    owner: "{{ sympa.unix_user }}"
    group: "{{ sympa.unix_group }}"
    recurse: yes

- name: Fix permissions
  command: "find {{ install_prefix }}/{{ sympa.install_dir_name }} -type d -exec chmod 0755 '{}' \\;"

- name: Ensuring archives directory is there
  file:
    path: "{{sympa.arc_path}}"
    state: directory
    owner: sympa
    group: sympa
    mode: 0755

- name: Ensuring lists directory is there
  file:
    path: "{{sympa.lists_path}}"
    state: directory
    owner: sympa
    group: sympa
    mode: 0755

