- name: Check Sympa tar.gz existence
  stat: path="{{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }}.tar.gz"
  register: sympa_archive_file

- name: Download Sympa tar.gz
  get_url:
    url: "{{ sympa.source }}/{{ sympa.version }}/sympa-{{ sympa.version }}.tar.gz"
    dest: "{{ install_prefix }}/{{ sympa.install_dir_name }}/src"
    sha256sum: "{{ sympa.sha256[sympa.version] }}"
  when: not sympa_archive_file.stat.exists

- name: Create the Sympa src directory
  file: path={{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }} state=directory
  
- name: Unpack the tarball
  unarchive: src={{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }}.tar.gz dest={{ install_prefix }}/{{ sympa.install_dir_name }}/src/ copy=no creates={{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }}/README

- name: Apply Sympa patches
  patch:
    src: "{{ item }}"
    basedir: "{{ install_prefix }}/{{ sympa.install_dir_name }}/src/{{ source_dir }}"
    strip: 1
  when: sympa.apply_patches
  with_fileglob: "{{ role_path }}/patches/{{ sympa.version }}/*.diff"

