---
# Configure Apache

- name: Install Apache2
  apt:
    name:
      - apache2
      - libapache2-mod-fcgid # FastCGI interface module for Apache 2
    state: present

- name: Enable CGI Apache module
  apache2_module: name=fcgid state=present
  notify: Restart Apache
  tags: apache
 
- name: install custom fcgid.conf file
  template: src=apache/fcgid.conf.j2 dest=/etc/apache2/mods-available/fcgid.conf
  notify: Restart Apache
  tags: apache

- name: Install Sympa web config
  template: src=apache/sympa_web.conf.j2 dest=/etc/apache2/conf-available/sympa.conf
  notify: Restart Apache
  tags: apache

- name: Enable Sympa web config
  shell: a2enconf sympa
