---
# Install and configure Sympa database

- name: Install required packages for MySQL
  apt: 
    name:
      - mysql-server
      - python-mysqldb # Required by Ansible
    state: present

- name: Enable MySQL server on boot
  service:
    name: mysql
    enabled: yes

- name: Ensure MySQL is started
  service:
    name: mysql
    state: started

# localhost needs to be the last item for idempotency, see
# http://ansible.cc/docs/modules.html#mysql-user
- name: 'Update Mysql Root Password'
  mysql_user:
    login_user: root
    login_password: "{{ db.root_password }}"
    ## Useful to update root user only if it is in the initial configuration state
    check_implicit_admin: yes
    name: root
    host: "{{ item }}"
    password: "{{ db.root_password }}"
    priv: "*.*:ALL,GRANT"
    state: present
  with_items:
    - 127.0.0.1
    - ::1
    - localhost

- name: Create sympa database if needed
  mysql_db:
    name: sympa
    login_user: root
    login_password: "{{ db.root_password }}"
    state: present

- name: Configure sympa user for MySQL server
  mysql_user:
    login_user: root
    login_password: "{{ db.root_password }}"
    name: "{{ sympa.db.app_user }}"
    password: "{{ sympa.db.app_password }}"
    host: "{{ item }}"
    priv: "sympa.*:ALL"
  with_items:
    - 127.0.0.1
    - ::1
    - localhost
