---
- name: Install required packages
  apt:
    name:
      - spamassassin
    state: present

- name: adjust spamassassin configuration
  lineinfile:
    path: /etc/spamassassin/local.cf
    regexp: '^{{ item }}'
    line: "{{ item }} {{ spamassassin.config.simple[item] }}"
    insertbefore: '^ifplugin'
  with_items: "{{ spamassassin.config.simple }}"
  notify: restart spamassassin

- name: adjust spamassassin scoring
  lineinfile:
    path: /etc/spamassassin/local.cf
    regexp: '^score {{ item }}'
    line: "score {{ item }} {{ spamassassin.config.score[item] }}"
    insertbefore: '^ifplugin'
  with_items: "{{ spamassassin.config.score }}"
  notify: restart spamassassin

- name: set report_safe to 0
  lineinfile:
    path: /etc/spamassassin/local.cf
    regexp: 'report_safe'
    line: "report_safe 0"

- name: Enable nightly channel update
  lineinfile:
    path: /etc/crontab
    line: "0 1     * * *   root    sa-update --gpgkey 6C6191E3 --channel updates.spamassassin.org ; service spamassassin restart >/dev/null 2>&1"
